server:
  port: 8080

spring:
  application:
    name: clinikai

  datasource:
    url: jdbc:postgresql://localhost:5432/clinikai
    username: clinikai
    password: clinikai

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    url: jdbc:postgresql://localhost:5432/clinikai
    password: clinikai
    user: clinikai
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    root: DEBUG
    org.flywaydb: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: TRACE

app:
  webhooks:
    zapi:
      secret: "CHANGE_ME_DEV_SECRET"
  security:
    jwt:
      secret: ${JWT_SECRET}
      access-token-minutes: 60
      issuer: clinikai

zapi:
  base-url: https://api.z-api.io
  instance-id: 3EB92EF66A5AA1272EF64A1F6B0D2773
  token: 927A39BB005A8132AE9F6DD9
  client-token: F65e23dc2bb014369926b6c6d764ebcc5S